### ISSUE TITLE
could not find bam file

### ISSUE THREAD

**Issue by Cristinex** [WGLab/LIQA#10]
It turned out to be error:
.bam does not exist!

I run the command and the bam file in the same folder, it cannot find it. How to solve this problem?

Thank you!

**Comment by huyustats** [comment]
Please specify your bam file using option "-bam"

**Comment by Cristinex** [comment]
Here was my command.

`liqa -task quantify -refgene <path>/xx.refgene -bam <path>/yy.bam -out <path>/output -max_distance 20 -f_weight 1`

And I did not add any suffix for output since I did not know what format should be.

I did specified my bam file with -bam. Thank you for your reply!!!

**Comment by huyustats** [comment]
Please use "ls -l <path>/yy.bam" to check it the file is there. Also, please sort and index the bam file before running LIQA. Thanks!

**Comment by Cristinex** [comment]
Thank you!! It work after indexing.

Another question, is it possible to use LIQA for hpv genome annotation? Since I downloaded hpv's gtf from [https://www.ncbi.nlm.nih.gov/assembly/GCF_000863945.3/](url)
and executed -task refgene. It turned out that 0 genes were processed. Was there any problem for this .gtf to be process?

**Comment by agouru55** [comment]
Hi yes, I did the same and I was able to output processed genes. Perhaps as done above, sort/index the BAM before LIQA, and ensure you have the latest version of LIQA as you run the quantify task again.

This step also usually only outputs genes with 2 or more isoforms, which is why you may be running into this issue
