### ISSUE TITLE
how to calculate TPM 

### ISSUE THREAD

**Issue by tebioinformatics** [WGLab/LIQA#41]
Hi, I'm an university student!

I used liqa-quantify, and I could gain 5 parameters (GeneName, IsoformNames, ReadPerGene_corrected, RelativeAbundance, infor_ratio). Is it possible to calculate TPM using only these five parameters? If not, what other parameters are needed? 

I need a specific solution!!

Thank you!

**Comment by agouru55** [comment]
Hi, thanks for your question and sorry for the delay! You probably wouldn't be able to calculate TPM alone with these parameters, since you'd likely need some sort of gene length parameter in addition to read counts (ReadPerGene_corrected). My best bet would be to find gene length from the isolated gene/isoform names, then perform calculations accordingly
