### ISSUE TITLE
error in liqa -diff

### ISSUE THREAD

**Issue by Saravanakumarselvaraj12** [WGLab/LIQA#46]
Hi.. i am running liqa for my 4 samples (2 in each condition). While running i encountered this issue.. DAS testing: Gene USP47 being processed...Error in while (testhalf & stepFactor < 11) { : 
  missing value where TRUE/FALSE needed
Error in if (grepl("Error", fit.H0) == T) { : 
  the condition has length > 1
Execution halted.. i tried all the possibilities but could not solve it. Could you kindly help me to resolve this issue?

**Comment by Saravanakumarselvaraj12** [comment]
DAS testing: Gene MRPS6 being processed...Error in while (testhalf & stepFactor < 11) { : 
  missing value where TRUE/FALSE needed
Error in optim(start, fn.opt, method = method, control = control) : 
  initial value in 'vmmin' is not finite
DAS testing: Gene SLC39A8 being processed...Error in while (testhalf & stepFactor < 11) { : 
  missing value where TRUE/FALSE needed
Error in optim(start, fn.opt, method = method, control = control) : 
  initial value in 'vmmin' is not finite
DAS testing: Gene THUMPD3 being processed...Error in while (testhalf & stepFactor < 11) { : 
  missing value where TRUE/FALSE needed
Error in optim(start, fn.opt, method = method, control = control) : 
  initial value in 'vmmin' is not finite
DAS testing: Gene PHF14 being processed...Error in while (testhalf & stepFactor < 11) { : 
  missing value where TRUE/FALSE needed
Error in while (testhalf & stepFactor < 11) { : 
  missing value where TRUE/FALSE needed
DAS testing: Gene VPS4A being processed...Error in while (testhalf & stepFactor < 11) { : 
  missing value where TRUE/FALSE needed
Error in optim(start, fn.opt, method = method, control = control) : 
  initial value in 'vmmin' is not finite
DAS testing: Gene ZNF106 being processed...Error in while (testhalf & stepFactor < 11) { : 
  missing value where TRUE/FALSE needed
Error in if (grepl("Error", fit.H0) == T) { : 
  the condition has length > 1
Execution halted

**Comment by agouru55** [comment]
Hello, please feel free to check within some of the closed issues such as #32 and #5 and a few others, as other users have run into this error. The optim function basically removes genes with expressions that failed in fitting the beta regression model. I don't seem to run into an error when running on the example data or any other sets. I'd first check the other closed issues and if your problem isn't resolved, be sure to check the format of your input file (esp because none of your genes were able to get processed) and if not I can take a look. Thanks!
